### ISSUE TITLE
Refonte du moteur de templates

### ISSUE THREAD

**Issue by AlixSperoza** [AlixSperoza/frash#158]
Transfert d'issues :
- [ ] Interpréter les object dans un foreach : #157 
- [ ] Paramètre pour ne pas afficher la bottom bar : #156 
- [ ] Indiquer ajout params AJAX directement dans le controller : #149 
- [ ] Dans une condition, @var == value peut call in_array : #115 
- [ ] Fonction "itvl" : #77 
- [ ] Fonction "index" : #76 
- [ ] Fonction "include" : #75 
- [ ] Fonction "for" : #73 
- [ ] Ajout de filtres et de regex/class personnalisés : #71 
- [ ] Intégrer les filtres : #70 
- [ ] Générer une erreur s'il y a plusieurs fois le même nom de [part] dans différents extends : #67 
- [ ] if start with "string" : #68 
- [ ] if match with "regex" : #66 
- [ ] if end with "string" : #65 
- [ ] Suppression du template après comparaison before_url/url, si la langue change : #64 

Fonctionnalités :
- [ ] Interpréter "$var["key"]->key" et "$var.key.key" de la même façon
- [ ] Enlever le nom du part dans end_part
- [ ] Intégrer les fonctions
- [ ] Dans les class de template, supprimer les variables ne content que ""
- [ ] Dans les class de template, supprimer les retours à la ligne inutiles
